/**
 * Brings up an ISOLATED copy of the full stack for the e2e suite, then seeds it.
 *
 * Isolation, end to end:
 *   - its own compose project name (`kindred-e2e`, see docker/env.ts) — the dev stack's
 *     containers, network and named volumes (caddy_data/caddy_config) are prefixed `kindred_`
 *     and untouched;
 *   - its own ports (8180/55440) — the dev stack's 8080/5432 are never dialled;
 *   - its own throwaway Postgres + attachments volumes (docker-compose.e2e.yml overrides the
 *     base file's bind mounts, which are NOT project-scoped and would otherwise point straight
 *     at the dev stack's ../data/postgres and ../data/attachments — see that file's header).
 *
 * Sequence: write deploy/.env.e2e -> `compose up --build -d` -> poll /api/v1/health -> copy
 * server/scripts/seed_demo.py into the api container and run it (it is not baked into the
 * image; server/Dockerfile only ships `app`, `alembic`, `alembic.ini`).
 *
 * Teardown (global-teardown.ts) always runs `compose ... down -v`, even on failure here,
 * because Playwright still invokes it once globalSetup has been called — but if THIS file
 * throws before the stack exists, there is nothing for teardown to remove; it tolerates that
 * (see its own comment).
 */
import { randomBytes } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import {
  COMPOSE_BASE,
  COMPOSE_OVERRIDE,
  DEPLOY_DIR,
  E2E_BASE_URL,
  E2E_HTTP_PORT,
  E2E_POSTGRES_PORT,
  E2E_PROJECT,
  ENV_FILE,
  SEED_ADMIN_PASSWORD,
  SEED_ADMIN_USERNAME,
  SEED_DEMO_SCRIPT,
} from './docker/env'

const HEALTH_TIMEOUT_MS = 120_000
const HEALTH_POLL_MS = 2_000

function compose(...args: string[]): void {
  execFileSync(
    'docker',
    ['compose', '-p', E2E_PROJECT, '--env-file', ENV_FILE, '-f', COMPOSE_BASE, '-f', COMPOSE_OVERRIDE, ...args],
    { cwd: DEPLOY_DIR, stdio: 'inherit' },
  )
}

function writeEnvFile(): void {
  const secretKey = randomBytes(32).toString('hex')
  const postgresPassword = randomBytes(16).toString('hex')

  // Deliberately no trailing comments on non-empty values (deploy/README.md: compose's
  // env_file parser only strips a trailing comment when the value IS empty).
  const contents = `
# Generated by web/e2e/global-setup.ts on every run. Git-ignored (deploy/.env.*). Do not hand-edit.
POSTGRES_USER=kindred_e2e
POSTGRES_PASSWORD=${postgresPassword}
POSTGRES_DB=kindred_e2e
DATABASE_URL=postgresql+asyncpg://kindred_e2e:${postgresPassword}@postgres:5432/kindred_e2e
SECRET_KEY=${secretKey}
SESSION_COOKIE_NAME=kindred_e2e_session
SESSION_TTL_HOURS=720
RATE_LIMIT_LOGIN_PER_MINUTE=5
SEED_ADMIN_USERNAME=${SEED_ADMIN_USERNAME}
SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
PUBLIC_BASE_URL=${E2E_BASE_URL}
CORS_ORIGINS=
KINDRED_SITE_ADDRESS=:8080
KINDRED_HTTP_PORT=${E2E_HTTP_PORT}
KINDRED_POSTGRES_PORT=${E2E_POSTGRES_PORT}
GOOGLE_MAPS_BROWSER_KEY=
GOOGLE_MAPS_SERVER_KEY=
VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_SUBJECT=mailto:e2e@example.org
ATTACHMENTS_DIR=/data/attachments
TZ=Europe/London
LOG_LEVEL=warning
`.trimStart()

  writeFileSync(ENV_FILE, contents, 'utf8')
}

async function waitForHealth(): Promise<void> {
  const deadline = Date.now() + HEALTH_TIMEOUT_MS
  let lastError = 'no attempt made'
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`${E2E_BASE_URL}/api/v1/health`)
      if (res.ok) {
        const body = (await res.json()) as { db?: string }
        if (body.db === 'ok') return
        lastError = `db status was "${body.db}"`
      } else {
        lastError = `HTTP ${res.status}`
      }
    } catch (cause) {
      lastError = cause instanceof Error ? cause.message : String(cause)
    }
    await new Promise((resolve) => setTimeout(resolve, HEALTH_POLL_MS))
  }
  // Health never came up — pull api logs before giving the caller a bare timeout.
  try {
    compose('logs', 'api')
  } catch {
    /* best-effort diagnostics */
  }
  throw new Error(`e2e stack never became healthy (last: ${lastError})`)
}

function seedDemoData(): void {
  // seed_demo.py is deliberately not baked into the api image (server/Dockerfile ships only
  // `app`, `alembic`, `alembic.ini` — see its comment on why). `docker compose cp` needs the
  // destination directory to exist first.
  compose('exec', '-T', 'api', 'mkdir', '-p', '/app/scripts')
  execFileSync(
    'docker',
    ['compose', '-p', E2E_PROJECT, 'cp', SEED_DEMO_SCRIPT, 'api:/app/scripts/seed_demo.py'],
    { cwd: DEPLOY_DIR, stdio: 'inherit' },
  )
  compose('exec', '-T', 'api', 'python', 'scripts/seed_demo.py')
}

export default async function globalSetup(): Promise<void> {
  console.log(`[e2e] writing ${ENV_FILE}`)
  writeEnvFile()

  console.log(`[e2e] docker compose -p ${E2E_PROJECT} up --build -d`)
  compose('up', '--build', '-d')

  console.log('[e2e] waiting for /api/v1/health ...')
  await waitForHealth()

  console.log('[e2e] seeding demo data (server/scripts/seed_demo.py) ...')
  seedDemoData()

  console.log(`[e2e] stack ready at ${E2E_BASE_URL}`)
}
