"""SQLAlchemy models.

Importing this package imports every model, which is what makes Alembic autogenerate see
the full metadata (``alembic/env.py`` imports this module for exactly that reason).
"""

from app.models.attachment import ATTACHMENT_SUBJECT_TYPES, Attachment
from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.comment import (
    COMMENT_SUBJECTS,
    NOTIFICATION_POLL_NUDGE,
    SUBJECT_POLL,
    Comment,
    Notification,
)
from app.models.family import (
    FAMILY_MANAGER_ROLES,
    FAMILY_ROLES,
    GEOCODE_STATUSES,
    HEX_COLOR_RE,
    INVITE_EXPIRY_CHOICES,
    INVITE_MODE_CREATE_FAMILY,
    LOCATION_BLOCKED_CONSENT,
    LOCATION_BLOCKED_FAMILY,
    LOCATION_BLOCKED_MEMBER,
    MAX_COLOR_SLOTS,
    ROLE_HEAD,
    ROLE_MEMBER,
    ROLE_SPOUSE,
    Family,
    FamilyMember,
    Invite,
    invite_status,
    is_invite_usable,
    location_block_reason,
    next_free_color,
    spouse_may_act_on,
    taken_colors,
)
from app.models.poll import (
    KIND_OPTIONS,
    KIND_SCORE_MATRIX,
    OPTIONS_POLL_SCORE,
    POLL_KINDS,
    POLL_STATUSES,
    SCORE_MAX,
    SCORE_MIN,
    STATUS_CLOSED,
    STATUS_OPEN,
    THUMBS,
    Poll,
    PollOption,
    PollScore,
)
from app.models.geo import EARTH_RADIUS_M, haversine_m, haversine_m_py
from app.models.session import LoginAttempt, Session
from app.models.suggestion import (
    GROUPABLE_CHILD_TYPES,
    STATUS_APPROVED,
    STATUS_PROPOSED,
    STATUS_REJECTED,
    STATUS_SCHEDULED,
    STATUS_SHORTLISTED,
    STATUS_TRANSITIONS,
    SUBJECT_SUGGESTION,
    SUGGESTION_STATUSES,
    SUGGESTION_TYPES,
    TYPE_ACCOMMODATION,
    TYPE_ACTIVITY,
    TYPE_MEAL,
    TYPE_REGION,
    Suggestion,
    centroid,
)
from app.models.setting import (
    SETTING_INSTANCE_NAME,
    SETTING_INVITE_ONLY,
    SETTING_REGISTRATION_OPEN,
    Setting,
)
from app.models.trip import (
    DEFAULT_VOTING_MODES,
    STAGE_DIRECTIONS,
    STAGES,
    VOTING_CATEGORIES,
    VOTING_MODES,
    Trip,
    TripCategorySetting,
    TripStageTransition,
    is_owner_of,
)
from app.models.trip_organiser import TripOrganiser
from app.models.user import THEME_PREFS, User, UserSettings

__all__ = [
    "EARTH_RADIUS_M",
    "GROUPABLE_CHILD_TYPES",
    "STATUS_APPROVED",
    "STATUS_PROPOSED",
    "STATUS_REJECTED",
    "STATUS_SCHEDULED",
    "STATUS_SHORTLISTED",
    "STATUS_TRANSITIONS",
    "SUBJECT_SUGGESTION",
    "SUGGESTION_STATUSES",
    "SUGGESTION_TYPES",
    "TYPE_ACCOMMODATION",
    "TYPE_ACTIVITY",
    "TYPE_MEAL",
    "TYPE_REGION",
    "Suggestion",
    "centroid",
    "haversine_m",
    "haversine_m_py",
    "THUMBS",
    "SUBJECT_POLL",
    "STATUS_OPEN",
    "STATUS_CLOSED",
    "SCORE_MIN",
    "SCORE_MAX",
    "POLL_STATUSES",
    "POLL_KINDS",
    "OPTIONS_POLL_SCORE",
    "NOTIFICATION_POLL_NUDGE",
    "KIND_SCORE_MATRIX",
    "KIND_OPTIONS",
    "COMMENT_SUBJECTS",
    "ATTACHMENT_SUBJECT_TYPES",
    "FAMILY_MANAGER_ROLES",
    "FAMILY_ROLES",
    "GEOCODE_STATUSES",
    "HEX_COLOR_RE",
    "INVITE_EXPIRY_CHOICES",
    "INVITE_MODE_CREATE_FAMILY",
    "LOCATION_BLOCKED_CONSENT",
    "LOCATION_BLOCKED_FAMILY",
    "LOCATION_BLOCKED_MEMBER",
    "DEFAULT_VOTING_MODES",
    "MAX_COLOR_SLOTS",
    "ROLE_HEAD",
    "ROLE_MEMBER",
    "ROLE_SPOUSE",
    "SETTING_INSTANCE_NAME",
    "SETTING_INVITE_ONLY",
    "SETTING_REGISTRATION_OPEN",
    "STAGE_DIRECTIONS",
    "STAGES",
    "THEME_PREFS",
    "VOTING_CATEGORIES",
    "VOTING_MODES",
    "Attachment",
    "Base",
    "Family",
    "FamilyMember",
    "Invite",
    "LoginAttempt",
    "Comment",
    "Notification",
    "Poll",
    "PollOption",
    "PollScore",
    "Session",
    "Setting",
    "TimestampMixin",
    "Trip",
    "TripCategorySetting",
    "TripOrganiser",
    "TripStageTransition",
    "UUIDPrimaryKeyMixin",
    "User",
    "UserSettings",
    "invite_status",
    "is_owner_of",
    "is_invite_usable",
    "location_block_reason",
    "next_free_color",
    "spouse_may_act_on",
    "taken_colors",
]
